services:

  proxy:
    image: nginx:1-alpine
    command: “/bin/sh -c ‘while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \”daemon off;\”‘”
    volumes:
      - ./scflows/public/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./scflows/public/nginx/auth/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./scflows/public/certbot/www/:/var/www/certbot/:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal-network
    restart: always

  certbot:
    image: certbot/certbot:latest
    entrypoint: “/bin/sh -c ‘trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'”
    volumes:
      - ./scflows/public/certbot/www/:/var/www/certbot/:rw
      - ./scflows/public/certbot/conf/:/etc/letsencrypt/:rw

  rabbitmq:
    image: rabbitmq:latest
    env_file:
      - .env
    restart: unless-stopped
    stop_grace_period: 3s
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - internal-network

  flows:
    build: ./
    env_file:
      - .env
    command: ["cron", "-f"]
    # command: python flows.py auto-schedule --dry-run --celery --force-first-run --overwrite
    depends_on:
      - celery
    volumes:
      - ./scflows/public:/scflows/public
    networks:
      - internal-network

  web:
    build: ./
    depends_on:
      - rabbitmq
    env_file:
      - .env
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 -m 007 'scflows:create_app()' --error-logfile - --access-logfile -
    # healthcheck:
    #   test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:18000/healthy}"
    #   interval: "60s"
    #   timeout: "3s"
    #   start_period: "5s"
    #   retries: 3
    ports:
      - 5000:5000
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - ./scflows/public:/scflows/public
    networks:
      - internal-network

  celery:
    build: ./
    command: celery --app worker:app worker -l info --autoscale=4,2
    depends_on:
      - rabbitmq
    # user: nobody
    env_file:
      - .env
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - ./scflows/public:/scflows/public
    networks:
      - internal-network

  flower:
    build: ./
    command: celery flower -l info -app worker:tasks
    depends_on:
      - celery
    user: nobody
    env_file:
      - .env
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - ./scflows/public:/scflows/public
    ports:
      - 5555:5555
    networks:
      - internal-network

networks:
  internal-network:
