services:
  rabbitmq:
    image: rabbitmq:latest
    env_file:
      - .env
    restart: unless-stopped
    stop_grace_period: 3s
    ports:
      - 5672:5672
      - 15672:15672

  flows:
    build: ./
    env_file:
      - .env
    command: ["cron", "-f"]
    # command: python flows.py auto-schedule --dry-run --celery --force-first-run --overwrite
    depends_on:
      - celery
    volumes:
      - ./scflows/public:/scflows/public

  web:
    build: ./
    depends_on:
      - rabbitmq
    env_file:
      - .env
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 -m 007 'scflows:create_app()' --error-logfile - --access-logfile -
    # healthcheck:
    #   test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:18000/healthy}"
    #   interval: "60s"
    #   timeout: "3s"
    #   start_period: "5s"
    #   retries: 3
    ports:
      - 5000:5000
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - ./scflows/public:/scflows/public

  celery:
    build: ./
    command: celery --app worker:app worker -l info --autoscale=4,2
    depends_on:
      - rabbitmq
    # user: nobody
    env_file:
      - .env
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - ./scflows/public:/scflows/public

  flower:
    build: ./
    command: celery flower -l info -app worker:tasks
    depends_on:
      - celery
    user: nobody
    env_file:
      - .env
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - ./scflows/public:/scflows/public
    ports:
      - 5555:5555
